### ISSUE TITLE
导入问题

### ISSUE THREAD

**Issue by Bore-TuDou** [gaoxiaosong/react-native-pure-navigation-bar#15]
你好 我是rn新手  我遇到一个这样的问题  就是我按照你们步骤 导入 使用NaviBar  第一次报错  原因是没有引入react-navigration模块  npm成功之后  继续使用 报错
Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.
  什么原因啊

**Comment by gxsshallot** [comment]
@fangbo111 你好，这是因为你使用的`react-navigation`需要在APP中建立导航栈，具体步骤参见[react-navigation官方网站](https://reactnavigation.org/zh-Hans/)。
