### ISSUE TITLE
默认样式设置问题

### ISSUE THREAD

**Issue by chenjunzhi** [gaoxiaosong/react-native-pure-navigation-bar#16]
InnerNaviBar.defaultProps.style.title = {
    fontSize: 18,
    lineHeight: 44,
    textAlignVertical: 'center',
    textAlign: 'center',
    color: 'white',
};

在项目初始化index.js文件中，添加上如上的全局设置代码，没有效果。

**Comment by chenjunzhi** [comment]
问题已解决

**Comment by wi100sh** [comment]
@chenjunzhi 
你好，能否分享下怎么解决，我也遇到这个问题，感谢！
InnerNaviBar.defaultProps.style.safeArea = {
    flex: 0,
    backgroundColor: '#444444',
};
修改导航栏背景色，没有效果。而直接修改源码中的背景色，则可以。

参考另外的帖子，解决方法如下：
InnerNaviBar.defaultProps.style={
    safeView: {
        flex: 0,
        backgroundColor: 'red',
    },
}
