### ISSUE TITLE
添加自定义style时，会报图片没有color属性警告

### ISSUE THREAD

**Issue by fang130tao** [gaoxiaosong/react-native-pure-navigation-bar#19]
<NaviBar
          style={{backgroundColor:'#ef5241',color:'white'}}>
   </NaviBar>

报错：图片没color的属性
原因为：我传入的style是设置字体的样式，所以有color，但是查看源码，你把字体的样式和返回图片使用的同一个方法（_combineStyle ），而此方法都会合并this.props.style，所以字体的样式会加到图片上，所以就报错了
源码：<Image
                    source={this.props.gobackImage}
                    style={this._combineStyle('gobackImage')}
            />
        _combineStyle = (key, innerStyle = undefined) => {
             const style = Array.isArray(innerStyle) ? innerStyle : [innerStyle];
             return [styles[key], ...style, this.props.style];
         };

建议：返回箭头图片的样式，单独用个style表示。或者在this._combineStyle（）方法中，做个区分加载

**Comment by gxsshallot** [comment]
@fang130tao 我不太确定你使用的版本号，最新版`1.4.9`的函数如下：
```javascript
_combineStyle = (key, innerStyle = undefined) => {
    const style = Array.isArray(innerStyle) ? innerStyle : [innerStyle];
    return [styles[key], ...style, this.props.style[key]];
};
```
这里`this.props.style`属性是一个对象，里面包含多个`key`(取值参见`src/style.js`里面的键)，每一个`key`对应一个组件的样式。

对于每个视图，会把三种样式进行合并：

1. 默认配置样式`styles[key]`。
1. 应用内部动态样式`innerStyle`。
1. 属性中的样式`this.props.style[key]`。

**Comment by summer88123** [comment]
no update
