### ISSUE TITLE
怎么隐藏返回按钮

### ISSUE THREAD

**Issue by Mikelulu** [gaoxiaosong/react-native-pure-navigation-bar#2]

**Comment by gaoxiaosong** [comment]
@Mikelulu leftElement=

**Comment by gaoxiaosong** [comment]
@Mikelulu `leftElement={null}`就可以了，因为默认`leftElement`是等于`GOBACK_BUTTON`的，如果不传，则是undefined使用默认值，所以传null即可。

**Comment by Mikelulu** [comment]
谢谢 ， 同一个页面隐藏和显示 怎么切换   就是加载webView的时候  有返回才显示返回键

**Comment by Mikelulu** [comment]
> @Mikelulu `leftElement={null}`就可以了，因为默认`leftElement`是等于`GOBACK_BUTTON`的，如果不传，则是undefined使用默认值，所以传null即可。
 同一个页面隐藏和显示 怎么切换 就是加载webView的时候 有返回才显示返回键

**Comment by Mikelulu** [comment]
leftElement={this.state.backButtonEnabled ? GOBACK_BUTTON : null}  这样好像可以实现

**Comment by gaoxiaosong** [comment]
@Mikelulu 原生的webview可以拦截网页JS函数调用，RN的我不太清楚怎么拦截。如果可以的话，拦截后`this.setState({showBack: true/false})`，然后在render显示导航条的地方：`leftElement={this.state.showBack ? GOBACK_BUTTON : null}`，其中需要`import NaviBar, {GOBACK_BUTTON} from 'react-native-pure-navigation-bar';`。
