### ISSUE TITLE
修改导航栏颜色，iPhonex的安全区域没有变化，修改的container的背景色

### ISSUE THREAD

**Issue by huangxiongbiao12** [gaoxiaosong/react-native-pure-navigation-bar#20]
![image](https://user-images.githubusercontent.com/14267929/58848673-0b1d0100-86ba-11e9-9980-2a9cc832c179.png)

**Comment by summer88123** [comment]
设置给safeView试一下

**Comment by summer88123** [comment]
@huangxiongbiao12 设置给safeView试一下

**Comment by huangxiongbiao12** [comment]
设置safeView可以了，3q
