### ISSUE TITLE
Big title functionality?

### ISSUE THREAD

**Issue by pvinis** [gaoxiaosong/react-native-pure-navigation-bar#5]
Is this supported for iOS? Will it ever be?

**Comment by youngxiaoran** [comment]
<iframe src="http://app.siweidaotu.com/#Xbf159c73840b6401851e2eb2dc5afb56" width="700px" height="500px" frameborder="0" scrolling="no"></iframe>

**Comment by gaoxiaosong** [comment]
@youngxiaoran What is it ??

**Comment by gaoxiaosong** [comment]
@pvinis [Big Title (iOS)](https://github.com/gaoxiaosong/react-native-pure-navigation-bar/wiki/BigTitle). This is the wiki for Big Title setting.
