### ISSUE TITLE
Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.

### ISSUE THREAD

**Issue by trinadhkoya** [gaoxiaosong/react-native-pure-navigation-bar#6]
Not able to run this , can you look into this and close it ASAP

**Comment by gaoxiaosong** [comment]
If you are using it in a view not in navigator, you can `import { InnerNaviBar } from 'react-native-pure-navigation-bar'`. It is the component without `withNavigation`. And you can set `leftElement={null}` to disable default back button, or set `onLeft={() => { do(); return false; }}` to override default `goback` action of back button.
